NUMPY 100  EXERCISES


#day 1 21st august
1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)


In [4]:
print("Numpy Version-->>",np.__version__)
np.show_config()


Numpy Version-->> 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ADNAN/anaconda3/Library/include
    lib directory: C:/Users/ADNAN/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ADNAN/anaconda3/Library/include
    lib directory: C:/Users/ADNAN/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
   

3. Create a null vector of size 10 (★☆☆)

In [5]:
vector=np.zeros(10)
print("Vector of zeros-->>",vector)


Vector of zeros-->> [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array (★☆☆)

In [6]:
array=np.ones((10,5))
print("Array of ones-->>",array)
size=array.size
items=array.itemsize
print("Size of array-->>",size)
print("Item size of array-->>",items)
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))
# Simpler alternative
print("%d bytes" % Z.nbytes)

Array of ones-->> [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Size of array-->> 50
Item size of array-->> 8
800 bytes
800 bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
np.info
print("Numpy info-->>\n",np.info(np.add))



print("TRRRYYYYING\n")



add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [8]:
arrray=np.zeros(10)
arrray[4]=1
print("Array with 1 at 4th index-->>",arrray)

Array with 1 at 4th index-->> [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
arrray = np.arange(10, 50)
print("Array of range-->>",arrray)

Array of range-->> [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)

In [10]:
array=array[::-1]
print("Reversed array-->>",array)

Reversed array-->> [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [4]:
array=np.arange(9).reshape(3, 3)
print("Array of 9 elements reshaped to 3x3-->>",array)

Array of 9 elements reshaped to 3x3-->> [[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [5]:
nonz=np.nonzero([1,2,0,0,4,0])
print("Non zero elements-->>",nonz)

Non zero elements-->> (array([0, 1, 4]),)


11. Create a 3x3 identity matrix (★☆☆)

In [6]:
m=np.eye(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 12. Create a 3x3x3 array with random values (★☆☆)

In [7]:
mm=np.random.random((3,3,3))
print(mm)

[[[0.28820048 0.11303479 0.50705322]
  [0.76847694 0.72797229 0.60143039]
  [0.2222797  0.54812566 0.76102713]]

 [[0.62120471 0.20024748 0.42662008]
  [0.66164736 0.55690405 0.48794761]
  [0.54252946 0.21774122 0.92945366]]

 [[0.0838564  0.13426774 0.63484467]
  [0.2509036  0.58424161 0.29951216]
  [0.22543156 0.12107521 0.58932776]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [8]:
z=np.random.random((10,10))
zmin,zmax=z.min(),z.max()
print("Min and Max of array-->>",zmin,zmax)

Min and Max of array-->> 0.012568114908471317 0.9773556260050705


14. Create a random vector of size 30 and find the mean value (★☆☆)

In [9]:
z=np.random.random(30)
mean=np.mean(z)
print("Mean of array-->>",mean)
print("Standard deviation of array-->>",np.std(z))

Mean of array-->> 0.5486322256195165
Standard deviation of array-->> 0.30119827698704404


 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [10]:
zz=np.ones((10,10))
zz[1:-1,1:-1]=0
print(zz)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [11]:
k= np.ones((5,5))
k = np.pad(k, pad_width=1, mode='constant', constant_values=0)
print(k)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


 17. What is the result of the following expression? (★☆☆)

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1


In [16]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

'''

0 * np.nan---->>Nan
nanExplanation: Any arithmetic operation involving NaN (Not a Number) propagates NaN.

np.nan == np.nan ---->>False
Explanation: By the IEEE 754 floating-point standard, NaN is not equal to anything, including itself.


np.inf > np.nan ----->> False
Explanation: Any relational comparison (>, <, >=, <=) involving NaN evaluates to False

np.nan - np.nan------>> nan
Explanation: Similar to multiplication, subtraction with NaN results in NaN


np.nan in set([np.nan]) ------>> True
Explanation: Even though np.nan == np.nan is False, 
Python sets check object identity/hashing during lookup,
 allowing the identical object stored in the set to be found.


 0.3 == 3 * 0.1 ------>> False
 Explanation: Due to the limitations of binary floating-point representation in computers,
   3 * 0.1 evaluates to approximately 0.30000000000000004 rather than exact 0.3.
'''

nan
False
False
nan
True
False


'\n\n0 * np.nan---->>Nan\nnanExplanation: Any arithmetic operation involving NaN (Not a Number) propagates NaN.\n\nnp.nan == np.nan ---->>False\nExplanation: By the IEEE 754 floating-point standard, NaN is not equal to anything, including itself.\n\n\nnp.inf > np.nan ----->> False\nExplanation: Any relational comparison (>, <, >=, <=) involving NaN evaluates to False\n\nnp.nan - np.nan------>> nan\nExplanation: Similar to multiplication, subtraction with NaN results in NaN\n\n\nnp.nan in set([np.nan]) ------>> True\nExplanation: Even though np.nan == np.nan is False, \nPython sets check object identity/hashing during lookup,\n allowing the identical object stored in the set to be found.\n\n\n 0.3 == 3 * 0.1 ------>> False\n Explanation: Due to the limitations of binary floating-point representation in computers,\n   3 * 0.1 evaluates to approximately 0.30000000000000004 rather than exact 0.3.\n'

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
Zk = np.diag(1+np.arange(4),k=-1)
print(Zk)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [18]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [19]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))
