NUMPY 100  EXERCISES


#day 1 21st august
1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)


In [2]:
print("Numpy Version-->>",np.__version__)
np.show_config()


Numpy Version-->> 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ADNAN/anaconda3/Library/include
    lib directory: C:/Users/ADNAN/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ADNAN/anaconda3/Library/include
    lib directory: C:/Users/ADNAN/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
   

3. Create a null vector of size 10 (★☆☆)

In [5]:
vector=np.zeros(10)
print("Vector of zeros-->>",vector)


Vector of zeros-->> [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array (★☆☆)

In [18]:
array=np.ones((10,5))
print("Array of ones-->>",array)
size=array.size
items=array.itemsize
print("Size of array-->>",size)
print("Item size of array-->>",items)
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))
# Simpler alternative
print("%d bytes" % Z.nbytes)

Array of ones-->> [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Size of array-->> 50
Item size of array-->> 8
800 bytes
800 bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [29]:
np.info
print("Numpy info-->>\n",np.info(np.add))



print("TRRRYYYYING\n")



add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)


In [30]:
arrray=np.zeros(10)
arrray[4]=1
print("Array with 1 at 4th index-->>",arrray)

Array with 1 at 4th index-->> [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [32]:
arrray = np.arange(10, 50)
print("Array of range-->>",arrray)

Array of range-->> [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


8. Reverse a vector (first element becomes last) (★☆☆)

In [34]:
array=array[::-1]
print("Reversed array-->>",array)

Reversed array-->> [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [38]:
array=np.arange(9).reshape(3, 3)
print("Array of 9 elements reshaped to 3x3-->>",array)

Array of 9 elements reshaped to 3x3-->> [[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)